base_model: "./models/indictrans2-en-indic-1B"
model_args:
  trust_remote_code: true
  use_fast_tokenizer: true
pairs: ["hi-en"]
data_dir: "data/clean/hi_en"
output_dir: "outputs/hi_en_r8"
seed: 42

lora:
  r: 8
  alpha: 16
  dropout: 0.05
  target_modules: ["q_proj","v_proj","k_proj","o_proj"]

quantization:
  load_in_4bit: true
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_compute_dtype: "float16"

train:
  lr: 1.0e-4
  batch_size: 4
  grad_accum: 16
  max_steps: 6000
  warmup_ratio: 0.03
  eval_every: 500
  save_every: 1000
  gradient_checkpointing: true
  fp16: true
  save_total_limit: 2

task:
  max_src_len: 256
  max_tgt_len: 192
  tags:
    style: ["formal","informal"]
    simplify: ["yes","no"]
  prompt_template: "<SRC_LANG> <TGT_LANG> <STYLE> <SIMPLIFY> ||| <TEXT>"
  
